// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SentimentAnalysis
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("comparative")]
        public double? Comparative { get; set; }

        [JsonProperty("sentimentText")]
        public string SentimentText { get; set; }

        [JsonProperty("sentiment")]
        public long? Sentiment { get; set; }

        [JsonProperty("isPositive")]
        public bool? IsPositive { get; set; }

        [JsonProperty("isNegative")]
        public bool? IsNegative { get; set; }

        [JsonProperty("normalizedScore")]
        public double? NormalizedScore { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
